name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.2', '3.3', '3.4']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: false
    
    - name: Bundle install
      run: |
        bundle config set --local without 'development'
        bundle install --jobs 4 --retry 3
    
    - name: Run StandardRB
      run: bundle exec standardrb
    
    - name: Run tests
      run: bundle exec rspec